name: widget_to_image_converter
description: "A Flutter FFI plugin to convert a widget to an image. Uses C library to convert the widget to an image."
version: 1.0.0
license: MIT
homepage: https://github.com/RuslanTsitser/widget_to_image_converter
repository: https://github.com/RuslanTsitser/widget_to_image_converter
issue_tracker: https://github.com/RuslanTsitser/widget_to_image_converter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
